### ISSUE TITLE
Could rpi-pulsecounter get a pulse from Diehl IZAR PULSE i ?

### ISSUE THREAD

**Issue by meepmeep** [rhernaus/rpi-pulsecounter#5]
Hi

I'm trying to get pulse from my Diehl [Izar Pulse meter ](https://www.diehl.com/metering/en/products-solutions/products-services/system-software/system-software-components/izar-pulse-i-fr/558116/).
I tried with a multimeter, and get a sound signal every liter with it.

but, when I plug it on my rpi3 (GND on pin 39 + GPIO 21) and start your docker app, no pulse is collected.
`{"pin":21,"impkwh":1,"topic":"hass/power/meter2/kw"}`

Does it need to have to be an electrical pulse ? 
Maybe I don't use the correct pin number ? (I tried with pin 40 and 21)

**Comment by rhernaus** [comment]
Hi,

Thank you for reaching out with your issue. I didn't imagine this would be used for a water meter, but it should work none the less.

Regarding the pin numbers, it seems that you're using the correct pin numbers for the Raspberry Pi 3. However, make sure that you're using the correct pin numbering scheme (BOARD) in your code. Based on the code, I'm using the BOARD numbering scheme (GPIO.setmode(GPIO.BOARD)), which means you should use the physical pin numbers on the Raspberry Pi board. For GPIO 21 in BOARD numbering, you should connect to pin 40.

Another possible issue could be the pull-up or pull-down resistor configuration. In the code, I'm using a pull-down resistor (GPIO.PUD_DOWN) for the input pin. However, depending on the pulse meter, you might need to use a pull-up resistor (GPIO.PUD_UP) instead. To test this, change the following line in the code:

`GPIO.setup(int(gpio["pin"]), GPIO.IN, pull_up_down=GPIO.PUD_DOWN)`
to
`GPIO.setup(int(gpio["pin"]), GPIO.IN, pull_up_down=GPIO.PUD_UP)`

**Comment by meepmeep** [comment]
Hi

Thank you for the answer ! I'm indeed mapping the pin with the **BCM** mode (so 40 -> GPIO21)
I mixed your code and another one using "`from gpiozero import Button`".

It works great ;)
